#!/usr/bin/env python3
"""Project Reality style squad leaders for a Mumble server.

Every channel directly under Root is a squad. The first person in a squad
(normally whoever created it) becomes its squad leader and is put in the
temporary group "sl" on that channel. Clients shout to Root + subchannels
restricted to group "sl", so only squad leaders hear each other.

If the squad leader leaves, the person who has been in the squad longest takes
over. The squad leader can hand over with "!sl <name>" in the squad's chat.

Settings come from environment variables (see squad-bot.env).
"""

import html
import logging
import os
import sys
import threading
import time

import Ice

SLICE_FILE = os.environ.get("MUMBLE_SLICE", os.path.join(os.path.dirname(os.path.abspath(__file__)), "MumbleServer.ice"))
SLICE_INCLUDE = os.environ.get("ICE_SLICE_DIR", "/usr/share/ice/slice")
ICE_HOST = os.environ.get("MUMBLE_ICE_HOST", "127.0.0.1")
ICE_PORT = int(os.environ.get("MUMBLE_ICE_PORT", "6502"))
ICE_SECRET = os.environ.get("MUMBLE_ICE_SECRET", "")
SERVER_ID = int(os.environ.get("MUMBLE_SERVER_ID", "1"))
SL_GROUP = os.environ.get("SL_GROUP", "sl")
SQUAD_PARENT = int(os.environ.get("SQUAD_PARENT_ID", "0"))  # 0 = Root
IGNORE_CHANNELS = {n.strip().lower() for n in os.environ.get("IGNORE_CHANNELS", "").split(",") if n.strip()}
LEADER_KEY_HINT = os.environ.get("LEADER_KEY_HINT", "V")
SETUP_ROOT_ACL = os.environ.get("SETUP_ROOT_ACL", "1") == "1"
RECONCILE_EVERY = 5.0

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("squad-bot")

Ice.loadSlice("", ["-I" + SLICE_INCLUDE, SLICE_FILE])
import MumbleServer  # noqa: E402  (generated by loadSlice)


class SquadManager:
    def __init__(self, server):
        self.server = server
        self.lock = threading.Lock()
        self.leader = {}      # channel id -> session of squad leader
        self.order = {}       # channel id -> sessions in the order they joined
        self.cleaned = set()  # (channel id, session) pairs already cleared of stale "sl" membership

    # --- helpers -------------------------------------------------------------------------

    def _is_squad(self, channel):
        return (channel.parent == SQUAD_PARENT and channel.id != SQUAD_PARENT
                and channel.name.strip().lower() not in IGNORE_CHANNELS)

    def _add(self, cid, session):
        self.server.addUserToGroup(cid, session, SL_GROUP)

    def _remove(self, cid, session):
        try:
            self.server.removeUserFromGroup(cid, session, SL_GROUP)
        except (MumbleServer.InvalidSessionException, MumbleServer.InvalidChannelException):
            pass  # user or channel already gone

    def _announce(self, cid, text):
        try:
            self.server.sendMessageChannel(cid, False, text)
        except MumbleServer.InvalidChannelException:
            pass

    def _tell(self, session, text):
        try:
            self.server.sendMessage(session, text)
        except MumbleServer.InvalidSessionException:
            pass

    def _make_leader(self, cid, session, users, channels, reason):
        self._add(cid, session)
        self.leader[cid] = session
        name = html.escape(users[session].name)
        squad = html.escape(channels[cid].name)
        log.info("%s is now squad leader of %s (%s)", users[session].name, channels[cid].name, reason)
        self._announce(cid, f"<b>{name}</b> is now squad leader of <b>{squad}</b>.")
        self._tell(session, f"You are squad leader of <b>{squad}</b>. Hold <b>{html.escape(LEADER_KEY_HINT)}</b> "
                            f"to talk to the other squad leaders. Type <b>!sl name</b> here to hand over.")

    # --- main logic ----------------------------------------------------------------------

    def reconcile(self):
        with self.lock:
            users = self.server.getUsers()        # session -> User
            channels = self.server.getChannels()  # id -> Channel
            squads = {cid for cid, c in channels.items() if self._is_squad(c)}

            members = {cid: set() for cid in squads}
            for session, u in users.items():
                if u.channel in members:
                    members[u.channel].add(session)

            # Forget squads that no longer exist
            for cid in list(self.order):
                if cid not in squads:
                    self.order.pop(cid, None)
                    self.leader.pop(cid, None)
            self.cleaned = {(c, s) for (c, s) in self.cleaned if c in members and s in members[c]}

            for cid in squads:
                present = members[cid]
                # Keep join order; newcomers go to the back (longest online first within one batch)
                order = [s for s in self.order.get(cid, []) if s in present]
                newcomers = sorted(present - set(order), key=lambda s: -users[s].onlinesecs)
                order.extend(newcomers)
                self.order[cid] = order

                current = self.leader.get(cid)

                # A newcomer might reuse the session id of someone who used to lead this squad;
                # make sure only the real leader is in the group.
                for s in order:
                    if s != current and (cid, s) not in self.cleaned:
                        self._remove(cid, s)
                        self.cleaned.add((cid, s))

                if current is not None and current not in present:
                    self._remove(cid, current)  # they moved to another channel (no-op if they disconnected)
                    self.leader.pop(cid, None)
                    current = None
                    if order:
                        self._make_leader(cid, order[0], users, channels, "previous leader left")
                elif current is None and order:
                    self._make_leader(cid, order[0], users, channels, "first in squad")

    def handover(self, sender, text):
        with self.lock:
            users = self.server.getUsers()
            channels = self.server.getChannels()
            me = users.get(sender.session)
            if me is None or me.channel not in self.leader:
                return
            cid = me.channel
            leader = self.leader.get(cid)
            target_name = text[3:].strip()
            if not target_name:
                current = users.get(leader)
                self._tell(sender.session, f"Squad leader: <b>{html.escape(current.name) if current else 'nobody'}</b>")
                return
            if sender.session != leader:
                self._tell(sender.session, "Only the squad leader can hand over.")
                return
            matches = [s for s, u in users.items() if u.channel == cid and u.name.lower() == target_name.lower()]
            if not matches:
                matches = [s for s, u in users.items() if u.channel == cid and u.name.lower().startswith(target_name.lower())]
            if len(matches) != 1:
                self._tell(sender.session, f"No single squad member matches <b>{html.escape(target_name)}</b>.")
                return
            new = matches[0]
            if new == leader:
                return
            self._remove(cid, leader)
            self.cleaned.add((cid, leader))
            self._make_leader(cid, new, users, channels, f"handed over by {me.name}")

    def ensure_root_acl(self):
        """Let everyone create temporary channels directly under Root (not inside squads)."""
        acls, groups, inherit = self.server.getACL(SQUAD_PARENT)
        own = [a for a in acls if not a.inherited]
        perm = MumbleServer.PermissionMakeTempChannel
        if any(a.group == "all" and a.userid == -1 and a.applyHere and (a.allow & perm) for a in own):
            return
        own.append(MumbleServer.ACL(applyHere=True, applySubs=False, inherited=False, userid=-1,
                                    group="all", allow=perm, deny=0))
        self.server.setACL(SQUAD_PARENT, own, [g for g in groups if not g.inherited], inherit)
        log.info("Root ACL updated: everyone may create temporary squad channels")


class Callback(MumbleServer.ServerCallback):
    def __init__(self, manager, wake):
        self.manager = manager
        self.wake = wake

    def userConnected(self, state, current=None): self.wake.set()
    def userDisconnected(self, state, current=None): self.wake.set()
    def userStateChanged(self, state, current=None): self.wake.set()
    def channelCreated(self, state, current=None): self.wake.set()
    def channelRemoved(self, state, current=None): self.wake.set()
    def channelStateChanged(self, state, current=None): self.wake.set()

    def userTextMessage(self, state, message, current=None):
        text = message.text.strip()
        if text.lower() == "!sl" or text.lower().startswith("!sl "):
            threading.Thread(target=self._handover, args=(state, text), daemon=True).start()

    def _handover(self, state, text):
        try:
            self.manager.handover(state, text)
        except Exception:
            log.exception("handover failed")


def connect(ic):
    meta = MumbleServer.MetaPrx.checkedCast(ic.stringToProxy(f"Meta:tcp -h {ICE_HOST} -p {ICE_PORT}"))
    if meta is None:
        raise RuntimeError("could not reach the Mumble server's Ice interface")
    server = meta.getServer(SERVER_ID)
    if server is None:
        raise RuntimeError(f"virtual server {SERVER_ID} not found")
    return server


def main():
    props = Ice.createProperties(sys.argv)
    props.setProperty("Ice.ImplicitContext", "Shared")
    props.setProperty("Ice.Default.EncodingVersion", "1.0")
    props.setProperty("Ice.MessageSizeMax", "65536")
    init = Ice.InitializationData()
    init.properties = props

    with Ice.initialize(init) as ic:
        if ICE_SECRET:
            ic.getImplicitContext().put("secret", ICE_SECRET)
        adapter = ic.createObjectAdapterWithEndpoints("SquadBot", f"tcp -h {ICE_HOST}")
        adapter.activate()

        wake = threading.Event()
        manager = None
        while True:
            try:
                if manager is None:
                    server = connect(ic)
                    manager = SquadManager(server)
                    if SETUP_ROOT_ACL:
                        manager.ensure_root_acl()
                    cb = MumbleServer.ServerCallbackPrx.uncheckedCast(adapter.addWithUUID(Callback(manager, wake)))
                    server.addCallback(cb)
                    log.info("Connected to Mumble server %d, managing squads", SERVER_ID)
                manager.reconcile()
            except (Ice.Exception, RuntimeError) as e:
                log.warning("Mumble connection problem (%s); retrying in 10s", e)
                manager = None
                time.sleep(10)
                continue
            except Exception:
                log.exception("unexpected error")
            wake.wait(RECONCILE_EVERY)
            wake.clear()
            time.sleep(0.2)  # let a burst of events settle


if __name__ == "__main__":
    main()
